# Generated by Django 5.2.4 on 2025-07-05 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='certifications',
            field=models.TextField(blank=True, help_text='Any relevant certifications (name, issuer, year)', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='education',
            field=models.TextField(blank=True, help_text='Your educational background (degree, institution, year)', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='github_profile',
            field=models.URLField(blank=True, help_text='Your GitHub profile URL', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='applicant',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='applicant',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the applicant', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Your personal website/portfolio URL', null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume_content_json',
            field=models.JSONField(blank=True, help_text='Structured JSON content used to generate the resume', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='title',
            field=models.CharField(blank=True, help_text="Professional title (e.g., 'Senior Software Engineer')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='experience',
            field=models.TextField(help_text='Describe your relevant work experience (include years)'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume_pdf',
            field=models.FileField(blank=True, help_text='Generated PDF resume', null=True, upload_to='resumes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=15),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['status'], name='jobs_applic_status_294c80_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['created_at'], name='jobs_applic_created_3a8b62_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['title'], name='jobs_applic_title_a9f3e1_idx'),
        ),
    ]
