# Generated by Django 5.2.4 on 2025-07-09 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_savedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_jobs_through', through='jobs.SavedJob', to=settings.AUTH_USER_MODEL),
        ),
    ]
