services:

  elsaticsearch:
    image: elasticsearch:8.13.4
    container_name: elasticsearch
    environment:   
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local